name: large-records-plugin-poc

dependencies:
  - base == 4.14.3.0 # ghc 8.10.7

executables:
  large-records-plugin-poc-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - large-records-plugin-poc

library:
  source-dirs: src
  dependencies:
    - ghc
    - lens
    - containers
    - mtl
    - generic-lens
    - uniplate
